# Generated by Django 5.2.2 on 2025-09-28 22:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_store', '0001_initial'),
        ('store', '0017_category_image_url_company_logo_url'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title_part1', models.CharField(default='ABOUT', max_length=100)),
                ('hero_title_part2', models.CharField(default='MOBILE CORNER', max_length=100)),
                ('hero_description', models.TextField(default='Your trusted partner in mobile technology since day one')),
                ('hero_background_video_url', models.URLField(blank=True, help_text='Hero background video URL')),
                ('certifications_title_part1', models.CharField(default='Official Certifications', max_length=100)),
                ('certifications_title_part2', models.CharField(default='& Trust Shields', max_length=100)),
                ('certifications_description', models.TextField(default='We are proud to be officially certified and authorized by leading mobile brands')),
                ('story_title', models.CharField(default='Our Story', max_length=100)),
                ('story_content', wagtail.fields.RichTextField(blank=True)),
                ('story_video_url', models.URLField(blank=True, help_text='Company story video URL')),
                ('partners_title_part1', models.CharField(default='Big Clients', max_length=100)),
                ('partners_title_part2', models.CharField(default='& Partners', max_length=100)),
                ('partners_description', models.TextField(default='Trusted by leading brands and thousands of satisfied customers')),
                ('stats_customers_count', models.IntegerField(default=10000)),
                ('stats_products_count', models.IntegerField(default=500)),
                ('stats_years_experience', models.IntegerField(default=10)),
                ('stats_brands_count', models.IntegerField(default=15)),
                ('gallery_title', models.CharField(default='Store Gallery', max_length=100)),
                ('gallery_description', models.TextField(default='Take a look at our premium store and facilities')),
                ('virtual_tour_url', models.URLField(blank=True, help_text='Virtual tour URL')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_content', wagtail.fields.RichTextField(blank=True)),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_content', wagtail.fields.RichTextField(blank=True)),
                ('why_choose_title', models.CharField(default='Why Choose Us', max_length=100)),
                ('why_choose_description', models.TextField(default='Discover what makes us the preferred choice for mobile technology')),
                ('testimonials_title', models.CharField(default='What Our Customers Say', max_length=100)),
                ('testimonials_description', models.TextField(default='Real experiences from real customers')),
                ('testimonials_video_url', models.URLField(blank=True, help_text='Customer testimonials video URL')),
                ('location_title', models.CharField(default='Visit Our Store', max_length=100)),
                ('location_address', models.TextField(default='Dubai Plaza, shop#13 basement, Bahawalpur, 63100')),
                ('location_phone1', models.CharField(default='+92 300 9681212', max_length=20)),
                ('location_phone2', models.CharField(default='+92 315 9682684', max_length=20)),
                ('location_email', models.EmailField(default='mobilercornerbwp@gmail.com', max_length=254)),
                ('location_maps_url', models.URLField(blank=True, help_text='Google Maps URL')),
                ('hours_monday_thursday', models.CharField(default='11:00 AM - 11:00 PM', max_length=50)),
                ('hours_saturday_sunday', models.CharField(default='12:00 PM - 11:00 PM', max_length=50)),
                ('hours_friday', models.CharField(default='Closed', max_length=50)),
                ('cta_title', models.CharField(default='Ready to Get Started?', max_length=100)),
                ('cta_description', models.TextField(default='Join thousands of satisfied customers who trust Mobile Corner')),
                ('cta_button_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_button_url', models.URLField(default='/store/')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title_part1', models.CharField(default='GET IN', max_length=50)),
                ('page_title_part2', models.CharField(default='TOUCH', max_length=50)),
                ('page_description', models.TextField(default="Have questions? We'd love to hear from you.")),
                ('contact_title', models.CharField(default='Contact Information', max_length=100)),
                ('address_label', models.CharField(default='Address', max_length=50)),
                ('address_text', models.TextField(default='Dubai Plaza, shop#13 basement, Bahawalpur, 63100')),
                ('address_url', models.URLField(blank=True, help_text='Google Maps URL')),
                ('phone_label', models.CharField(default='Phone', max_length=50)),
                ('phone1', models.CharField(default='+92 300 9681212', max_length=20)),
                ('phone2', models.CharField(default='+92 315 9682684', max_length=20)),
                ('email_label', models.CharField(default='Email', max_length=50)),
                ('email', models.EmailField(default='mobilercornerbwp@gmail.com', max_length=254)),
                ('hours_title', models.CharField(default='Business Hours', max_length=100)),
                ('hours_weekdays_label', models.CharField(default='Monday - Thursday', max_length=50)),
                ('hours_weekdays_time', models.CharField(default='11:00 AM - 11:00 PM', max_length=50)),
                ('hours_weekend_label', models.CharField(default='Saturday - Sunday', max_length=50)),
                ('hours_weekend_time', models.CharField(default='12:00 PM - 11:00 PM', max_length=50)),
                ('hours_friday_label', models.CharField(default='Friday', max_length=50)),
                ('hours_friday_time', models.CharField(default='Closed', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StorePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Our Products', max_length=100)),
                ('page_subtitle', models.TextField(default='Discover our premium collection of mobile devices and accessories')),
                ('page_banner_url', models.URLField(blank=True, help_text='Page banner image URL')),
                ('show_categories', models.BooleanField(default=True, help_text='Show category filter')),
                ('show_companies', models.BooleanField(default=True, help_text='Show brand filter')),
                ('show_price_filter', models.BooleanField(default=True, help_text='Show price filter')),
                ('show_search', models.BooleanField(default=True, help_text='Show search functionality')),
                ('products_per_page', models.IntegerField(default=12, help_text='Number of products per page')),
                ('show_product_badges', models.BooleanField(default=True, help_text='Show featured/new badges')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image_url',
            field=models.URLField(blank=True, help_text='About section image URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_title',
            field=models.CharField(default='About Mobile Corner', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_video_url',
            field=models.URLField(blank=True, help_text='About section video URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_description',
            field=models.TextField(default='Discover our premium collection of mobile devices'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_title',
            field=models.CharField(default='FEATURED PRODUCTS', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_section_description',
            field=models.TextField(default='Experience the difference with our premium services'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_section_title',
            field=models.CharField(default='Why Choose Mobile Corner?', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_logo_url',
            field=models.URLField(blank=True, help_text='Hero logo image URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_main_title',
            field=models.CharField(default='MOBILE CORNER', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_line1',
            field=models.CharField(default='Your Premium Destination for Mobile Technology', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_line2',
            field=models.CharField(default='Experience Excellence in Every Device', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_description',
            field=models.TextField(default='Subscribe to get the latest updates on new arrivals and offers'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_title',
            field=models.CharField(default='Stay Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='productpage',
            name='delivery_info',
            field=models.TextField(blank=True, help_text='Delivery information'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='show_company_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='show_related_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='show_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='show_specifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='warranty_info',
            field=models.TextField(blank=True, help_text='Warranty information'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='additional_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Additional product description'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_pages', to='store.product'),
        ),
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(help_text='Brand logo image URL')),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_logos', to='cms_store.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CertificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Optional certification image URL')),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cms_store.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class (e.g., fas fa-shield-alt)', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cms_store.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(help_text='Gallery image URL')),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cms_store.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_buttons', to='cms_store.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Customer photo URL')),
                ('testimonial_text', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='cms_store.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us_items', to='cms_store.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductListPage',
        ),
    ]
