# Generated by Django 5.2.2 on 2025-09-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_store', '0002_aboutpage_contactpage_storepage_and_more'),
        ('store', '0017_category_image_url_company_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cms_pages', to='store.product'),
        ),
    ]
