# Generated by Django 5.2.2 on 2025-09-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_store', '0003_alter_productpage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_button_url',
            field=models.URLField(blank=True),
        ),
    ]
