# Generated by Django 5.2.2 on 2025-09-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_store', '0004_alter_aboutpage_cta_button_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storepage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL to prevent duplicate content issues'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics ID (e.g., GA_MEASUREMENT_ID)', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO. e.g., mobile phones, smartphones, technology', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Prevent search engines from following links on this page'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing. Maximum 200 characters.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_image',
            field=models.URLField(blank=True, help_text='Image URL for social media sharing (1200x630px recommended)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing (Open Graph). Maximum 95 characters.', max_length=95),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL to prevent duplicate content issues'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics ID (e.g., GA_MEASUREMENT_ID)', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO. e.g., mobile phones, smartphones, technology', max_length=500),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Prevent search engines from following links on this page'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing. Maximum 200 characters.', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='og_image',
            field=models.URLField(blank=True, help_text='Image URL for social media sharing (1200x630px recommended)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing (Open Graph). Maximum 95 characters.', max_length=95),
        ),
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL to prevent duplicate content issues'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics ID (e.g., GA_MEASUREMENT_ID)', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO. e.g., mobile phones, smartphones, technology', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Prevent search engines from following links on this page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing. Maximum 200 characters.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.URLField(blank=True, help_text='Image URL for social media sharing (1200x630px recommended)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing (Open Graph). Maximum 95 characters.', max_length=95),
        ),
        migrations.DeleteModel(
            name='CategoryPage',
        ),
        migrations.DeleteModel(
            name='CompanyPage',
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
        migrations.DeleteModel(
            name='ProductPage',
        ),
        migrations.DeleteModel(
            name='StorePage',
        ),
    ]
