# Generated by Django 5.2.2 on 2025-09-30 23:17

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_store', '0005_remove_companypage_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='cta_button_text',
            new_name='cta_button1_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_button_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='gallery_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='stats_brands_count',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='testimonials_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='why_choose_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_button1_url',
            field=models.URLField(blank=True, help_text='First CTA button URL'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_button2_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_button2_url',
            field=models.URLField(blank=True, help_text='Second CTA button URL'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gallery_title_part1',
            field=models.CharField(default='OUR', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gallery_title_part2',
            field=models.CharField(default='SHOWROOM', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_address_label',
            field=models.CharField(default='Address', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_description',
            field=models.TextField(default='Located in the heart of Bahawalpur, our store is your gateway to the latest mobile technology. Visit us for hands-on experience with our products and personalized assistance from our expert team.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_email_label',
            field=models.CharField(default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_hours_label',
            field=models.CharField(default='Business Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_phone_label',
            field=models.CharField(default='Phone', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_vision_title_part1',
            field=models.CharField(default='OUR', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_vision_title_part2',
            field=models.CharField(default='MISSION', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_customers_label',
            field=models.CharField(default='Happy Customers', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_description',
            field=models.TextField(default="Our achievements speak for themselves. Here's what we've accomplished together with our amazing customers and partners."),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_products_label',
            field=models.CharField(default='Products Sold', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_support_label',
            field=models.CharField(default='Support', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_support_text',
            field=models.CharField(default='24/7', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_title',
            field=models.CharField(default='BY THE NUMBERS', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_years_label',
            field=models.CharField(default='Years Experience', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='testimonials_title_part1',
            field=models.CharField(default='WHAT OUR', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='testimonials_title_part2',
            field=models.CharField(default='CUSTOMERS SAY', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='virtual_tour_button_text',
            field=models.CharField(default='Take Virtual Tour', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='why_choose_title_part1',
            field=models.CharField(default='WHY CHOOSE', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='why_choose_title_part2',
            field=models.CharField(default='MOBILE CORNER', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_description',
            field=models.TextField(default='Join thousands of satisfied customers who have made Mobile Corner their trusted tech partner.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_title',
            field=models.CharField(default='READY TO EXPERIENCE THE DIFFERENCE?', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_description',
            field=models.TextField(default='Step inside our modern showroom and experience the future of mobile technology'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='location_title',
            field=models.CharField(default='VISIT US', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_content',
            field=wagtail.fields.RichTextField(default='To democratize access to premium mobile technology by providing authentic, high-quality devices and exceptional customer service that exceeds expectations. We strive to be the bridge between cutting-edge technology and the Pakistani market.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='MISSION', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stats_customers_count',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stats_products_count',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stats_years_experience',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonials_description',
            field=models.TextField(default='Real stories from real customers who have experienced the Mobile Corner difference'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_content',
            field=wagtail.fields.RichTextField(default="To become Pakistan's leading mobile technology retailer, known for innovation, trust, and customer-centricity. We envision a future where every Pakistani has access to the latest mobile technology to enhance their digital lifestyle."),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_title',
            field=models.CharField(default='VISION', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='why_choose_description',
            field=models.TextField(default='Experience the difference that sets us apart'),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_image_url', models.URLField(blank=True, help_text='Customer photo URL')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='cms_store.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
