# Generated by Django 5.2.2 on 2025-10-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_store', '0006_rename_cta_button_text_aboutpage_cta_button1_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_description',
            field=models.TextField(default='View our official certifications and authorization documents'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_image1_title',
            field=models.CharField(default='Apple Authorization', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_image1_url',
            field=models.URLField(blank=True, help_text='First documentation image URL'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_image2_title',
            field=models.CharField(default='Samsung Partnership', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_image2_url',
            field=models.URLField(blank=True, help_text='Second documentation image URL'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_image3_title',
            field=models.CharField(default='Quality Certificate', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_image3_url',
            field=models.URLField(blank=True, help_text='Third documentation image URL'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='documentation_title',
            field=models.CharField(default='Official Documentation', max_length=100),
        ),
    ]
