# Generated by Django 5.2.2 on 2025-10-02 00:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_store', '0007_aboutpage_documentation_description_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#00D4FF', help_text='Hex color code for category', max_length=7)),
                ('icon_class', models.CharField(default='fas fa-tag', help_text='FontAwesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO. e.g., mobile phones, smartphones, technology', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL to prevent duplicate content issues')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing (Open Graph). Maximum 95 characters.', max_length=95)),
                ('og_description', models.TextField(blank=True, help_text='Description for social media sharing. Maximum 200 characters.', max_length=200)),
                ('og_image', models.URLField(blank=True, help_text='Image URL for social media sharing (1200x630px recommended)')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics ID (e.g., GA_MEASUREMENT_ID)', max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('nofollow', models.BooleanField(default=False, help_text='Prevent search engines from following links on this page')),
                ('hero_title', models.CharField(default='MOBILE CORNER BLOG', max_length=100)),
                ('hero_subtitle', models.CharField(default='Latest Tech News, Reviews & Insights', max_length=200)),
                ('hero_description', models.TextField(default='Stay updated with the latest mobile technology trends, product reviews, and expert insights from Mobile Corner.')),
                ('hero_background_image', models.URLField(blank=True, help_text='Hero background image URL')),
                ('featured_posts_title', models.CharField(default='Featured Articles', max_length=100)),
                ('featured_posts_count', models.IntegerField(default=3, help_text='Number of featured posts to display')),
                ('show_categories', models.BooleanField(default=True, help_text='Show categories section')),
                ('categories_title', models.CharField(default='Browse by Category', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO. e.g., mobile phones, smartphones, technology', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL to prevent duplicate content issues')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing (Open Graph). Maximum 95 characters.', max_length=95)),
                ('og_description', models.TextField(blank=True, help_text='Description for social media sharing. Maximum 200 characters.', max_length=200)),
                ('og_image', models.URLField(blank=True, help_text='Image URL for social media sharing (1200x630px recommended)')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics ID (e.g., GA_MEASUREMENT_ID)', max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('nofollow', models.BooleanField(default=False, help_text='Prevent search engines from following links on this page')),
                ('featured_image', models.URLField(help_text='Main blog post image URL')),
                ('excerpt', models.TextField(help_text='Short description for blog listing', max_length=300)),
                ('author_name', models.CharField(default='Mobile Corner Team', max_length=100)),
                ('author_image', models.URLField(blank=True, help_text='Author profile image URL')),
                ('author_bio', models.TextField(blank=True, help_text='Author bio')),
                ('content', wagtail.fields.RichTextField(help_text='Main blog post content')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured posts section')),
                ('reading_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('show_social_share', models.BooleanField(default=True, help_text='Show social media sharing buttons')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_store.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, to='cms_store.blogtag')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
