# Generated by Django 5.2.2 on 2025-06-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_dealer_purchase_purchaseitem_sale_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sub_dealer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='deviceidentifier',
            name='product',
        ),
        migrations.RemoveField(
            model_name='deviceidentifier',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='deviceidentifier',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='device_identifier',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='DeviceIdentifier',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
