# Generated by Django 5.2.2 on 2025-06-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_sale_sub_dealer_remove_purchase_dealer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
