# Generated by Django 5.2.2 on 2025-06-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cartitem_color_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='image_url',
        ),
    ]
