# Generated by Django 5.2.2 on 2025-06-21 12:53

from django.db import migrations

def fix_orderitem_none_values(apps, schema_editor):
    OrderItem = apps.get_model('store', 'OrderItem')
    
    # Fix order items with None price or quantity
    for item in OrderItem.objects.all():
        if item.price is None:
            # Set price to product's current discounted price
            item.price = item.product.discounted_price
            item.save()
            print(f"Fixed price for OrderItem {item.id}")
        
        if item.quantity is None:
            # Set quantity to 1 as default
            item.quantity = 1
            item.save()
            print(f"Fixed quantity for OrderItem {item.id}")

def reverse_fix_orderitem_none_values(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orderitem_color'),
    ]

    operations = [
        migrations.RunPython(fix_orderitem_none_values, reverse_fix_orderitem_none_values),
    ]
