# Generated by Django 5.2.2 on 2025-06-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_fix_orderitem_none_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pending', 'Pending - Will be discussed with representative'), ('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment')], default='pending', max_length=50),
        ),
    ]
