"""
Django settings for setting project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2%^2s!i9h+xwormt--ur=q_wr5_g3upcp0ar)0bqcq#iaxb#1c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    'user_auth',  # 
    'store',
    'chatbot',  # Chatbot for phone recommendations
    'inventory_erp',  # ERP system for inventory management
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'setting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
if not DEBUG:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_auth.User'


UNFOLD = {
    "SITE_TITLE": "Mobile Corner",
    "SITE_HEADER": "Mobile Corner Admin",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("logo-light.JPG"),  # both modes, optimise for 32px height
    # "SITE_ICON": {
    #     "light": lambda request: static("icon-light.svg"),  # light mode
    #     "dark": lambda request: static("icon-dark.svg"),  # dark mode
    # },
    "SITE_LOGO": {
        "light": lambda request: static("logo-light.JPG"),  # light mode
        "dark": lambda request: static("logo-dark.JPG"),  # dark mode
    },
    "SITE_SYMBOL": "speed",  # symbol from icon set
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("logo-light.JPG"),
        },
    ],
    "SHOW_HISTORY": True, # show/hide "History" button, default: True
    "SHOW_VIEW_ON_SITE": True, # show/hide "View on site" button, default: True
    "SHOW_BACK_BUTTON": True, # show/hide "Back" button on changeform in header, default: False
    "LOGIN": {
        "image": lambda request: static("bg.jpg"),
        "title": "Welcome to Bit and Bytes System",
        "description": "Please login to access the system",
        
        # "redirect_after": lambda request: reverse_lazy("admin:APP_MODEL_changelist"),
    },
    "STYLES": [
        lambda request: static("css/admin.css"),
    ],
    "SCRIPTS": [

    ],
    "COLORS": {
        "base": {
            "50": "255 255 255",  # Light mode background
            "100": "245 245 245",  # Light mode surface
            "200": "229 229 229",  # Light mode border
            "300": "209 213 219",  # Light mode subtle text
            "400": "102 102 102",  # Light mode secondary text
            "500": "64 64 64",     # Light mode primary text
            "600": "45 45 45",     # Dark mode text
            "700": "38 38 38",     # Dark mode surface
            "800": "26 26 26",     # Dark mode background
            "900": "19 19 19",     # Darker background
            "950": "13 13 13",     # Darkest background
        },
        "primary": {
            "50": "245 245 245",   # mc-white in light mode
            "100": "229 229 229",  # mc-accent light hover
            "200": "212 212 212",  # mc-accent light active
            "300": "245 245 245",  # mc-accent
            "400": "156 156 156",  # mc-light-grey
            "500": "64 64 64",     # mc-grey
            "600": "45 45 45",     # mc-dark
            "700": "26 26 26",     # mc-black
            "800": "19 19 19",     # Darker shade
            "900": "13 13 13",     # Darkest shade
            "950": "0 0 0",        # Pure black
        },        "font": {
            "subtle-light": "var(--color-base-400)",    # Light mode secondary text
            "subtle-dark": "var(--color-base-400)",     # Dark mode secondary text
            "default-light": "var(--color-base-700)",   # Light mode primary text
            "default-dark": "var(--color-base-100)",    # Dark mode primary text
            "important-light": "var(--color-base-800)", # Light mode important text
            "important-dark": "var(--color-base-50)",   # Dark mode important text
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
    },

}
