# Generated by Django 5.2.2 on 2025-06-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_erp', '0002_company_remove_deviceidentifier_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Device Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='device',
            name='minimum_price',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='notes',
        ),
        migrations.AddField(
            model_name='device',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount or percentage value', max_digits=10),
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sku',
            field=models.CharField(default='', editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory_erp.company'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory_erp.devicecategory'),
        ),
    ]
