# Generated by Django 5.2.2 on 2025-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_erp', '0003_devicecategory_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
